# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

#[[main]]
#  name = "Blog"
#  pageRef = "posts"
#  weight = 10


[[main]]
name = "Main"
pageRef = "posts"
weight = 10

#[[main]]
#name = "ç¬”è®°"
#pageRef = "ç¬”è®°"
#weight = 15

[[main]]
name = "å…¨éƒ¨"
pageRef="all"
weight = 20

[[main]]
name = "ç®—æ³•"
pageRef = "algorithm"
weight = 30

[[main]]
name = "å½’ç±»"
pageRef = "tags"
weight = 32

[[main]]
name = "å‹é“¾ğŸ§‘â€ğŸ¤â€ğŸ§‘"
pageRef = "friend"
weight = 40

[[main]]
name = "æ›´å¤šğŸ˜º"
weight = 40

[[main]]
parent = "æ›´å¤šğŸ˜º"
name = "ç”µå½±ğŸ¥"
pageRef = "media"
weight = 41

[[main]]
parent = "æ›´å¤šğŸ˜º"
pageRef = "music"
name = "éŸ³ä¹ğŸµ"
weight = 42

[[main]]
parent = "æ›´å¤šğŸ˜º"
pageRef = "life-about"
name = "ç”Ÿæ´»ç›¸å…³ğŸŒ¿"
weight = 42

[[main]]
parent = "æ›´å¤šğŸ˜º"
pageRef = "ç¬”è®°"
name = "ç¬”è®°(æ¯”è¾ƒä¹±)ğŸ¦"
weight = 43

[[main]]
parent = "æ›´å¤šğŸ˜º"
pageRef = "ç¼–ç¨‹è¯­è¨€"
name = "ç¼–ç¨‹è¯­è¨€ğŸ’»"
weight = 44


#[[main]]
#  name = "Parent"
#  weight = 20

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20

[[footer]]
name = "ç³»åˆ—æ–‡ç« "
pageRef = "tags"
weight = 10

[[footer]]
name = "å…³äºæˆ‘"
pageRef = "info"
weight = 20

[[footer]]
name = "æ–‡æ¡£"
pageRef = "doc"
weight = 40

[[footer]]
name = "äº‹é¡¹"
pageRef = "tasks"
weight = 16