# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

#[[main]]
#  name = "Blog"
#  pageRef = "posts"
#  weight = 10


[[main]]
name = "ä¸»é "
pageRef = "all"
weight = 10

#[[main]]
#name = "ç­†è¨˜"
#pageRef = "ç­†è¨˜"
#weight = 15

[[main]]
name = "é‡‘èåˆ†æ"
pageRef="/tags/é‡‘èåˆ†æ"
weight = 20


[[main]]
name = "æ¨™ç±¤"
pageRef = "tags"
weight = 32

[[main]]
name = "æˆ¿åœ°ç”¢"
url = "/tags/æˆ¿åœ°ç”¢/"
weight = 41

[[main]]
name = "æ’­å®¢ğŸµ"
url = "/tags/æ’­å®¢/"
weight = 40

[[main]]
name = "æ³•å¾‹"
url = "/tags/æ³•å¾‹/"
weight = 40

[[main]]
name = "æ›´å¤š"
weight = 44


#[[main]]
#parent = "æ›´å¤š"
#pageRef = "music"
#name = "éŸ³æ¨‚ğŸµ"
#weight = 42

[[main]]
parent = "æ›´å¤š"
pageRef = "life"
name = "ç”Ÿæ´»ç›¸é—œ"
weight = 42

#[[main]]
#parent = "æ›´å¤š"
#pageRef = "ç¬”è®°"
#name = "ç¬”è®°(æ¯”è¾ƒä¹±)ğŸ¦"
#weight = 43

#[[main]]
#parent = "æ›´å¤š"
#pageRef = "ç¼–ç¨‹è¯­è¨€"
#name = "ç¼–ç¨‹è¯­è¨€ğŸ’»"
#weight = 44


#[[main]]
#  name = "Parent"
#  weight = 20

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20

[[footer]]
name = "ç³»åˆ—æ–‡ç« "
pageRef = "tags"
weight = 10

[[footer]]
name = "é—œæ–¼æˆ‘"
pageRef = "about"
weight = 20

[[footer]]
name = "æ–‡æ¡£"
pageRef = "doc"
weight = 40

[[footer]]
name = "äº‹é¡¹"
pageRef = "tasks"
weight = 16